name: CI

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
       auth_header="$(git config --local --get http.https://github.com/.extraheader)"
       git submodule sync --recursive
       git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Setup Go Runtime
      uses: actions/setup-go@v2-beta
      with:
        go-version: '1.13.8'
    - name: NPM cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Go cache
      uses: actions/cache@v1
      with:
        path: ${{ env.GITHUB_WORKSPACE }}/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('.ci/install_deps.sh') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: setup env
      shell: bash
      run: |
        echo "::set-env name=GOPATH::${{ github.workspace }}/go"
        echo "::add-path::${{ github.workspace }}/go/bin"
    - name: Install Deps
      run: bash .ci/install_deps.sh
    - name: Output hugo verison
      shell: bash
      run: hugo version
    - name: Build site
      shell: bash
      run: hugo -v

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: NPM cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Test Deps
      run: bash .ci/install_test_deps.sh
    - name: Run test script
      run: bash .ci/test.sh

  deploy:
    needs:
    - build
    - test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
       auth_header="$(git config --local --get http.https://github.com/.extraheader)"
       git submodule sync --recursive
       git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Setup Go Runtime
      uses: actions/setup-go@v2-beta
      with:
        go-version: '1.13.8'
    - name: NPM cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Go cache
      uses: actions/cache@v1
      with:
        path: ${{ env.GITHUB_WORKSPACE }}/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('.ci/install_deps.sh') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install Deps
      run: bash .ci/install_deps.sh
    - name: setup env
      shell: bash
      run: |
        echo "::set-env name=GOPATH::${{ github.workspace }}/go"
        echo "::add-path::${{ github.workspace }}/go/bin"
    - name: Install Deps
      run: bash .ci/install_deps.sh
    - name: Build site
      shell: bash
      run: hugo -v
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        SSH: true
        BRANCH: gh-pages
        FOLDER: public
        GIT_CONFIG_NAME: Github Deploy
        GIT_CONFIG_EMAIL: noreply@github.com
